const LOGIN_TYPES = {
    SET_EMAIL: 'SET_EMAIL',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_ERROR: 'SET_ERROR',
    SET_FIRST_SUBMIT: 'SET_FIRST_SUBMIT',
    EXIT: 'EXIT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
};

export default LOGIN_TYPES;